redis: Support Sentinel with SSL
celery/kombu pull request #1275
Opened 2020-11-19 09:16 UTC by auvipy

Use the SentinelManagedSSLConnection when SSL is enabled for the
transport.

2020-11-22 00:31 UTC, matusvalo requested changes
The unittests are failing.

2020-11-23 06:16 UTC, AbdealiJK commented
@auvipy Just saw that you created this - Thanks :)
I've modified the PR to create the `SentinelManagedSSLConnection` class directly in Kombu for now - until https://github.com/andymccurdy/redis-py/pull/1419 gets merged.

This way @matusvalo - the unit tests will pass and we can switch to the redis-py class when that gets merged

This PR relates to: https://github.com/celery/celery/issues/6455

2020-11-23 13:06 UTC, auvipy reviewed
now just flake8 n doc styles are failing

2020-11-23 14:01 UTC, AbdealiJK commented
Thanks for the bump :) Fixed

2020-11-23 19:12 UTC, matusvalo commented
Thanks for PR. It seems fine. Could you add also unittests?

2020-11-24 07:19 UTC, AbdealiJK commented
@matusvalo - Added unit test.
For the integration test - Yeah, I'm not sure where to start on that

2020-11-24 07:59 UTC, AbdealiJK commented
Seems like the test failure is now due to azure-servicebus releasing a new version 7 hours ago :(
https://pypi.org/project/azure-servicebus/7.0.0/

2020-11-28 22:06 UTC, matusvalo reviewed
Thank you @AbdealiJK. I have just one comment regarding unittests.

About Integration test, see the following comment: https://github.com/celery/kombu/issues/1254#issuecomment-735296395

2020-12-02 08:46 UTC, AbdealiJK commented on t/unit/transport/test_redis.py
> +                assert params.get('ssl') is None
Fixed

2020-12-03 06:50 UTC, merged