Add fanout support to kombu
celery/kombu pull request #1280
Opened 2020-12-06 02:29 UTC by yhal-nesi

I am are trying to use celery with filesystem transport, but it doesn't support control commands without the fanout. This patch implements the required functionality. 

* It requires control_folder defined and created. Could probably make it a subfolder of "in" or "out" for compatibility. Or make fanout support conditional on its existence? 
* Exchange bindings are never deleted. Is there any function in Channel class for that? 
* _put_fanout doesn't make use of the routing key. Not sure if this is needed for some functionality? The documentation for FanoutExchange doesn't say anything about this method but celery control doesn't work without it. 

I've also made it create a directory for each queue, so that one huge queue like celeryev doesn't slow everything down.

2020-12-07 20:36 UTC, matusvalo commented
Hi @yhal-nesi. Thank you for your PR. I will review it soon

2020-12-20 00:03 UTC, matusvalo requested changes
Here is my first review of the code:
1. Please make sure that flake8 is happy
2. Please update the doc string of the module. PR Adds additonal Transport Options which are not mentioned there. Also some high level information about directory structure would be great (even the control files)
3. please update the unittests with the tests of newly added code.

2020-12-20 00:54 UTC, matusvalo reviewed
Regarding your questions:

> It requires control_folder defined and created. Could probably make it a subfolder of "in" or "out" for compatibility. Or make fanout support conditional on its existence?

I think that we can introduce new directory, but it needs to be documented in module

> Exchange bindings are never deleted. Is there any function in Channel class for that?

It would be great to support also unbinging. There is method for that:
https://github.com/celery/kombu/blob/d62ba3cd96a73a4440c4a62d1e575dee82b5ba9e/kombu/transport/virtual/base.py#L570

> _put_fanout doesn't make use of the routing key. Not sure if this is needed for some functionality? The documentation for FanoutExchange doesn't say anything about this method but celery control doesn't work without it.

To be honest, I cannot answer this question right now. In general, fanout should not need routing key.

2020-12-20 00:54 UTC, matusvalo commented on kombu/transport/filesystem.py
> +            queue_val = (routing_key or '', pattern or '', queue or '' )
Please use namedtuple here. Define it as global data structure.

2020-12-20 00:54 UTC, matusvalo commented on kombu/transport/filesystem.py
> +    def _queue_bind(self, exchange, routing_key, pattern, queue):
Can we call `get_table()` function instead of duplicating of the code?

2020-12-20 00:54 UTC, matusvalo commented on kombu/transport/filesystem.py
> +            d.fileno = lambda: d_fileno
Can we define structure/adapter in global scope with proper comments?

2022-03-15 15:30 UTC, closed without merging

2022-03-15 15:31 UTC, auvipy commented
fixed in another PR