fix: non kombu json message decoding in SQS transport
celery/kombu pull request #1306
Opened 2021-03-06 11:24 UTC by moaddib666

Fix the case with custom messages decoding in SQS transport
Use cases:
1) Celery with custom consumer
2) PUB/SUB with Custom publisher [SNS+SQS]
3) Non kombu/celery protocols

2021-03-06 14:53 UTC, auvipy requested changes
can you also add a test for the changes?

2021-03-06 15:13 UTC, moaddib666 commented
> can you also add a test for the changes?

Hi, sure.

2021-03-06 18:28 UTC, moaddib666 commented
Updated. Also, I've interested in backporting following changes to the celery 4.* as well, please advise what should be done for it ?

2021-03-07 07:39 UTC, moaddib666 commented
Also looks like i would fix the issue described above https://github.com/celery/kombu/issues/1181#issue-607011906

2021-03-07 08:34 UTC, auvipy approved these changes

2021-03-07 08:35 UTC, merged