SQS Broker - handle STS authentication with AWS
celery/kombu pull request #1322
Opened 2021-03-23 15:08 UTC by galCohen88

STS token requires being refreshed after certain period of time. 

In the PR I added the functionality of creating the token and refreshing it once timeout reached

2021-03-23 15:36 UTC, galCohen88 commented
@thedrow @auvipy WDYT?

2021-03-24 03:07 UTC, auvipy requested changes
the approach seems ok, can you add tests for this as well?

2021-03-24 03:07 UTC, auvipy commented on kombu/transport/SQS.py
> +                raise UndefinedQueueException(("Queue with name '{}' must be defined in "
we can use f"" string here

2021-03-24 10:45 UTC, galCohen88 commented on kombu/transport/SQS.py
> +                raise UndefinedQueueException(("Queue with name '{}' must be defined in "
done

2021-03-24 10:49 UTC, galCohen88 commented
@auvipy Will add tests later today

2021-03-24 13:10 UTC, thedrow commented
@galCohen88 FYI, I've invited you to the team.

2021-03-24 14:23 UTC, thedrow requested changes

2021-03-24 14:23 UTC, thedrow commented on kombu/transport/SQS.py
> +                                               f" in 'predefined_queues'."))
```suggestion
                raise UndefinedQueueException(f"Queue with name '{queue}' must be defined"
                                                                     " in 'predefined_queues'.")
```

2021-03-24 14:23 UTC, thedrow commented on kombu/transport/SQS.py
> +                return self._predefined_queue_clients[queue]
Extract this to a helper function.

2021-03-24 14:23 UTC, thedrow commented
> 
> 
> the approach seems ok, can you add tests for this as well?

There's a label for requiring the user to add tests. I just added it.

2021-03-25 14:53 UTC, galCohen88 commented
@thedrow added helper method
@auvipy added tests

2021-03-26 07:01 UTC, galCohen88 commented on kombu/transport/SQS.py
> +    def handle_sts_session(self, queue, q):
changed

2021-03-26 08:49 UTC, thedrow commented
I need to review the documentation but overall this looks good.

2021-03-28 13:46 UTC, auvipy approved these changes

2021-03-29 08:35 UTC, thedrow approved these changes

2021-03-29 08:35 UTC, merged