Move pytest.importorskip to run earlier
celery/kombu pull request #1346
Opened 2021-05-29 21:11 UTC by felixonmars

Currently pytest fails to collect tests when `azure` is not present. Moving the pytest.importorskip clause before `from kombu.transport import azureservicebus` fixes it.

```
==================================== ERRORS ====================================
__________ ERROR collecting t/unit/transport/test_azureservicebus.py ___________
ImportError while importing test module '/build/python-kombu/src/kombu-5.1.0/t/unit/transport/test_azureservicebus.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
t/unit/transport/test_azureservicebus.py:12: in <module>
    from kombu.transport import azureservicebus
kombu/transport/azureservicebus.py:66: in <module>
    import azure.core.exceptions
E   ModuleNotFoundError: No module named 'azure'
```

2021-05-30 05:10 UTC, auvipy requested changes
can you adjust the lint error please?

2021-05-30 15:04 UTC, felixonmars commented
> can you adjust the lint error please?

Should I add #noqa to all these three lines?

2021-06-09 19:10 UTC, matusvalo commented
Yes please use # noqa to silence linter.

2021-06-11 07:21 UTC, matusvalo approved these changes

2021-06-11 07:21 UTC, merged