Prevent caching of oid in pidbox
celery/kombu pull request #1394
Opened 2021-09-29 20:57 UTC by matusvalo

oid is not cached anymore due race conditions of oid in celery. Caching
oid is causing following exception:

OperationalError("
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
",)

This exception seems to be occuring when multiple celery workers
contains same oid.

Fixes #1063

2021-09-29 21:00 UTC, matusvalo commented
Marking as draft for now. Let's wait for confirmation of this fix.

2021-09-30 13:59 UTC, auvipy commented
looks good

2021-10-04 09:10 UTC, thedrow commented
Hold up, how does this work if the OID changes every time?
How do multiple workers end up with the same OID?

2021-10-04 16:00 UTC, thedrow requested changes
I still have questions about this.

2021-10-04 21:14 UTC, matusvalo commented
> Hold up, how does this work if the OID changes every time?

OID won't change everytime. The generation of OID is bound to CPU, thread and object ID - see 

https://github.com/celery/kombu/blob/5ef5e22638035a6c412e949a2fbc5d44b7b088b2/kombu/common.py#L49-L55

Hence in the same process and thread and for each pidbox object the `oid_from()` function will return **the same** oid.

> How do multiple workers end up with the same OID?

The problem is with caching. The cache is stored in the heap and hence it is replicated across processes during fork() when new worker is spawned. Even thread local storage won't help -see following proof:

```python
import threading
import multiprocessing
mydata = threading.local()
mydata.x = 1

def f():
    print('f: ', mydata.x)

print('main process:', mydata.x)
t1 = threading.Thread(target=f)
t2 = threading.Thread(target=f)
print('starting t1')
t1.start()
print('starting t2')
t2.start()

p = multiprocessing.Process(target=f)
print('starting p')
p.start()
```

Running this script will print one for subprocess and raise attribute error for each thread. It means subthreads of process has local variable but subprocess **not**.

The same holds for pidbox oid - see example below:
```python
import multiprocessing
from kombu import pidbox

m = pidbox.Mailbox('unittest')
print(m.oid)

def getoid():
    print('getoid: ', m.oid)

p = multiprocessing.Process(target=getoid)
print('starting p')
p.start()

print(m.oid)
```

In this case both master process and subprocess **will share the oid** which is wrong:

```python
>>> import multiprocessing
>>> from kombu import pidbox
>>>
>>> m = pidbox.Mailbox('unittest')
>>> print(m.oid)
b8001cb8-1ae5-36f5-87f4-2660008969ec
>>>
>>> def getoid():
...     print('getoid: ', m.oid)
...
>>> p = multiprocessing.Process(target=getoid)
>>> print('starting p')
starting p
>>> p.start()
>>>
>>> print(m.oid)getoid:  b8001cb8-1ae5-36f5-87f4-2660008969ec

b8001cb8-1ae5-36f5-87f4-2660008969ec
>>>
```

> Each thread generates a new OID, so how there is a clash?

See my explanation above

2021-10-05 10:46 UTC, thedrow approved these changes
Thank you for the analysis.
This is a bug in `cached_property`'s implementation, it seems.

2021-10-05 10:51 UTC, thedrow commented
Note that the PyPy integration tests build is failing because we now only support 3.7 and above.

2021-10-05 11:09 UTC, merged

2021-10-05 11:20 UTC, matusvalo commented
> This is a bug in cached_property's implementation, it seems.

The bug in celery is due combination of cached_property, wrong usage of thread local storage.

I will add also unittests for this PR (99% done)

2021-10-05 11:25 UTC, thedrow commented
Oh, sorry.
I already merged the PR.
You can add the unit tests in another PR. :smile: