SQS: Fix message arg in backoff policy
celery/kombu pull request #1496
Opened 2022-02-25 17:07 UTC by matmarczak

Hi!

I just found an error in SQS implementation regarding backoff tasks. There was already notion of this [here](https://github.com/celery/kombu/pull/1372) or [here](https://github.com/celery/kombu/issues/1358). I still experience this problem when backoff policy is defined explicitly. [Prepared small example to reproduce issue](https://gitlab.com/amonowy/celery-sqs-reproduce). Fix is in this PR.

I'm open to comments and happy to improve this PR!

2022-02-27 13:49 UTC, auvipy requested changes
can you fix the lint error please?

2022-02-27 17:06 UTC, thedrow requested changes

2022-02-27 17:06 UTC, thedrow commented on kombu/transport/SQS.py
> +            self.extract_task_name_and_number_of_retries(message)
Shouldn't we get the message using `message = self._delivered[delivery_tag]`?
This PR breaks the class' public API and I'd rather avoid doing that.

2022-03-03 12:09 UTC, thedrow approved these changes
This is much better. Thanks!

2022-03-04 06:10 UTC, auvipy approved these changes

2022-03-04 06:14 UTC, merged