Add fanout to filesystem
celery/kombu pull request #1499
Opened 2022-03-03 12:06 UTC by karajan1001

Looks like #1280 is stale? 

filesystem transport lacks of fanout support.

1. Add fanout support to filesystem transport.
2. Add a unit test for it.

2022-03-07 13:26 UTC, karajan1001 commented on kombu/transport/filesystem.py
> +                return [exchange_queue_t(*q) for q in exchange_table]
Please use namedtuple here. Define it as global data structure.

from  https://github.com/celery/kombu/pull/1280#discussion_r546299433

2022-03-07 13:27 UTC, karajan1001 commented on kombu/transport/filesystem.py
> +    def _queue_bind(self, exchange, routing_key, pattern, queue):
Can we call get_table() function instead of duplicating of the code?

from https://github.com/celery/kombu/pull/1280#discussion_r546299811

2022-03-07 13:28 UTC, karajan1001 commented on kombu/transport/filesystem.py
> +        queues = self.get_table(exchange)
Can we define structure/adapter in global scope with proper comments?

from https://github.com/celery/kombu/pull/1280/files/d62ba3cd96a73a4440c4a62d1e575dee82b5ba9e#r546300210

But I removed these lines of code.

2022-03-07 21:55 UTC, matusvalo commented
I have added feedback but:
1. unittests are failing - did not go in deep why but they needs to be fixed
2. The PR contains also formatting changes. They should be not part of this PR.

2022-03-10 09:41 UTC, auvipy commented on kombu/transport/filesystem.py
> +        filename = os.path.join(self.control_folder, filename)
did you considered using pathlib instead?

2022-03-10 12:53 UTC, karajan1001 commented on kombu/transport/filesystem.py
> +        file = self.control_folder / f"{exchange}.exchange"
Use `pathlib` for the path management.

2022-03-14 20:41 UTC, matusvalo commented
LGTM for me except two small points:
* control_folder is not documented in docstring in the beginning of the file.
* I am not 100% sure whether `@cachedproperty` on top of control_folder is good idea. We had several problems with cached_property. Is there any reason to have it there? Does it make sense to have there only `@property` instead?

2022-03-15 05:38 UTC, auvipy requested changes
control_folder is not documented in docstring in the beginning of the file.
    I am not 100% sure whether @cachedproperty on top of control_folder is good idea. We had several problems with cached_property. Is there any reason to have it there? Does it make sense to have there only @property instead?

2022-03-15 14:20 UTC, auvipy approved these changes

2022-03-15 14:21 UTC, merged

2022-04-14 06:41 UTC, karajan1001 commented
Excuse me, is there any schedule for the next release?

2022-05-18 07:23 UTC, pmrowla commented
@thedrow are there any updates on when the next kombu release will be available? We are getting close to being ready to release our own downstream product that depends on this feature

2022-05-18 09:47 UTC, auvipy commented
> @thedrow are there any updates on when the next kombu release will be available? We are getting close to being ready to release our own downstream product that depends on this feature

wait next week please

2022-06-01 05:52 UTC, pmrowla commented
@auvipy any updates?

2022-06-21 07:20 UTC, auvipy commented
> @auvipy I see that the 5.3 milestone for celery+kombu keeps getting pushed back, is there any chance we could just get a limited 5.2.x kombu release with this patch included?

no, 5.3a1 this week.