Annotate `utils/uuid.py` and `utils/text.py`
celery/kombu pull request #1514
Opened 2022-04-09 12:25 UTC by Kludex

Related to #1511

2022-04-10 13:09 UTC, thedrow commented on kombu/utils/text.py
> +from ctypes import cast
Do we need to import this?

2022-04-10 13:24 UTC, Kludex commented on kombu/utils/text.py
> +from ctypes import cast
No, it's wrong.

2022-04-10 13:24 UTC, Kludex commented on kombu/utils/text.py
> +from ctypes import cast
```suggestion
```

2022-04-10 13:25 UTC, Kludex commented on kombu/utils/text.py
> +from ctypes import cast
Thanks 🙏

2022-04-12 13:59 UTC, auvipy requested changes
needs a rebase

2022-04-12 14:39 UTC, merged