Annotate `abstract.py`
celery/kombu pull request #1522
Opened 2022-04-11 19:07 UTC by Kludex

2022-04-11 19:13 UTC, Kludex commented
Why is there a bot that commits on my branch..........

2022-04-12 05:12 UTC, auvipy requested changes
please rebase & try to reduce the usage of Any types https://sethmlarson.dev/blog/tests-arent-enough-case-study-after-adding-types-to-urllib3#anything-but-any

2022-05-04 18:28 UTC, Kludex commented on kombu/abstract.py
> +    cls: Type[_ObjectType], kwargs: Dict[str, Any]
This `Any` is alright.

2022-05-04 18:28 UTC, Kludex commented on kombu/abstract.py
> +    attrs: Tuple[Tuple[str, Any], ...] = ()
The thing here is that each `attr` can really be `Any`, and `str` is the name of the `attr`. It looks fine as well.

2022-05-04 18:28 UTC, Kludex commented on kombu/abstract.py
> +        def f(obj: Any, type: Callable[[Any], Any]) -> Any:
Here is the only place that we can try to improve... I'm not sure what can be a good replacement tho...

2022-05-04 18:29 UTC, Kludex commented
rebased 👍

2022-05-15 07:17 UTC, auvipy approved these changes

2022-05-15 07:17 UTC, merged