add managed identity support to azure storage queue
celery/kombu pull request #1631
Opened 2022-12-17 23:24 UTC by jasonwbarnett

The title is self-explanatory.

2022-12-18 07:14 UTC, auvipy requested changes
why 1.5 and not 1.12.0

2022-12-18 07:14 UTC, auvipy commented on requirements/extras/azurestoragequeues.txt
> +azure-identity>=1.5.0
```suggestion
azure-identity>=1.12.0
```

2022-12-18 14:00 UTC, jasonwbarnett commented
> why 1.5 and not 1.12.0

I just thought to give a broader support for folks who might be running an older version. In reality I don't know what this is used for so it is fine to be the latest as well. I'll update the PR later when I'm done traveling.

2022-12-19 14:42 UTC, jasonwbarnett commented
@auvipy I forgot to mention that this has been tested and is working in our production environment.

2022-12-19 21:15 UTC, jasonwbarnett commented
I reviewed the failing integration tests and it appears to be only redis and completely unrelated to this PR. Is that true?

2022-12-20 04:44 UTC, auvipy commented
yes that is true

2022-12-20 05:04 UTC, auvipy commented
should we also document the change?

2022-12-20 14:53 UTC, jasonwbarnett commented
> yes that is true

👍 

> should we also document the change?

Yes. I thought I already did in the header of the file. Is there somewhere else to document the change? Please let me know and I will write the docs.

2022-12-20 15:42 UTC, jasonwbarnett commented
I tried refining the documentation even further. Let me know if I formatted them correctly, I've never used rst.

2022-12-21 08:03 UTC, auvipy commented
here https://github.com/celery/kombu/pull/1634 mostly pypy integration tests are failing

2022-12-21 13:02 UTC, jasonwbarnett commented
> here #1634 mostly pypy integration tests are failing

@auvipy Should I do anything more on this PR or is this PR acceptable in it's current state to be eventually merged when you are ready from a project perspective?

2022-12-21 13:27 UTC, auvipy commented
let me stabilize the CI little bit more, then you can pull from main branch

2022-12-26 15:05 UTC, thedrow approved these changes
LGTM

2022-12-26 18:51 UTC, auvipy approved these changes

2022-12-26 18:51 UTC, merged