fix: don't crash on 'utf-8' messages
celery/kombu pull request #1690
Opened 2023-04-08 16:08 UTC by pankgeorg

when a message has an `properties`.`body_encoding` of `utf-8` (e.g. the default on https://github.com/node-celery-ts/node-celery-ts), celery workers crash with an error `AttributeError: 'NoneType' object has no attribute 'decode'`. `utf-8` is functionally equivalent to not providing an encoding, so this should be good.

2023-04-08 16:35 UTC, auvipy requested changes
can you please add unit tests for the changes?

2023-04-08 16:59 UTC, pankgeorg commented
Yes I would love to! can you help be a bit figuring out where the related tests are?

2023-04-08 17:01 UTC, auvipy commented
https://github.com/celery/kombu/tree/main/t/unit/transport

2024-06-23 05:22 UTC, auvipy reviewed
this should be the primary place for adding tests 

https://github.com/celery/kombu/blob/main/t/unit/transport/virtual/test_base.py

2024-07-02 08:10 UTC, auvipy approved these changes

2024-07-02 08:11 UTC, merged