chore(ci): improve CI
celery/kombu pull request #1707
Opened 2023-05-11 17:50 UTC by stegayet

Improvements found while I was working on https://github.com/celery/kombu/pull/1705.

- Use exact tag for `setup-python` GH action.
- Get rid of dash stripping step for PyPy 3.9 version as [setup-python GH action supports using `pypy3.9` reference](https://github.com/actions/setup-python#basic-usage).

2023-05-13 12:17 UTC, stegayet commented
Probably got a lead on CI integration tests failure (unrelated to this PR), taking a look.

2023-05-14 11:20 UTC, auvipy requested changes
can you please re base?

2023-05-14 11:41 UTC, stegayet commented
Rebased, there will still be failures from lint job, addressing these issues in https://github.com/celery/kombu/pull/1718.

2023-05-14 12:07 UTC, auvipy approved these changes

2023-05-14 12:13 UTC, merged