azure service bus: fix TypeError when using Managed Identities
celery/kombu pull request #1825
Opened 2023-11-27 12:57 UTC by marnikow

When trying the new version of Kombu I get the following error:
```
TypeError("argument of type 'DefaultAzureCredential' is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 112, in start
    self.on_start()
  File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 135, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 169, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 230, in startup_info
    conninfo=self.app.connection().as_uri(),
  File "/usr/local/lib/python3.8/dist-packages/kombu/connection.py", line 715, in as_uri
    return self.transport.as_uri(
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/azureservicebus.py", line 484, in as_uri
    if ":" in credential:
TypeError: argument of type 'DefaultAzureCredential' is not iterable
```
Since I don't understand the meaning of the as_url function I just fixed the error locally. Feedback is welcome :)

2023-12-19 12:50 UTC, auvipy approved these changes

2023-12-19 13:27 UTC, auvipy requested changes
we might not need the print output on the final version

2023-12-19 13:27 UTC, auvipy commented on t/unit/transport/test_azureservicebus.py
> +    print(conn.as_uri(True))
```suggestion
```

2023-12-19 13:27 UTC, auvipy commented on t/unit/transport/test_azureservicebus.py
> +    print(conn.as_uri(True))
```suggestion
```

2023-12-19 13:27 UTC, auvipy commented on t/unit/transport/test_azureservicebus.py
> +    print(conn.as_uri(True))
```suggestion
```

2023-12-19 13:28 UTC, auvipy commented
also can you please check if the rtd docs build failures is not related to this PR?

2023-12-29 02:03 UTC, 50-Course commented
> also can you please check if the rtd docs build failures is not related to this PR?

Going through the log file, I am only able to deduce that the error isn't related to this PR. At least not that I know of. By my understanding,

> Problem in your project's configuration. No default configuration file found at repository's root. See https://docs.readthedocs.io/en/stable/config-file/

Seems to be an issue from the `docs/conf.py` which am yet to fully go through. The `.readthedocs.yml` configuration file seemed untouched as well. Please let me know if I am overlooking something.

CC: @auvipy

2023-12-29 09:15 UTC, merged

2023-12-29 09:16 UTC, auvipy commented
thanks