Add support for mongodb+srv scheme
celery/kombu pull request #1976
Opened 2024-04-03 21:36 UTC by H4ad

If we try run kombu with scheme `mongodb+srv`, it will break during URL parsing.

2024-05-04 06:30 UTC, auvipy requested changes
can you please add some tests for the changes?

2024-05-06 11:26 UTC, H4ad commented
@auvipy Unless you have a valid connection using mongodb+srv, I don't think is possible to add tests due to how this scheme is resolved using DNS.

2024-06-03 23:10 UTC, Nusnus commented
> @auvipy Unless you have a valid connection using mongodb+srv, I don't think is possible to add tests due to how this scheme is resolved using DNS.

I understand - would it be ok to ask for you to do some manual testing and at least share here the logs so we can have at least a minimal confirmation of it working?

P.S
From a quick review it appears to be ok, but I’d want at least something to hold on to if we can’t add automatic testing 🙏

2024-06-04 13:04 UTC, H4ad commented
I did a monkey-patch on my code to use this change, I've been using since I opened this PR, this is the logs from yesterday:

![Screenshot from 2024-06-04 09-47-47](https://github.com/celery/kombu/assets/12551007/0159e548-0466-45f4-a46a-37d39c2166af)

My monkey patch code is basically this:

```py
from kombu.transport.mongodb import Channel
from pymongo import uri_parser


def monkey_patch_channel_parse_uri(self, scheme="mongodb://"):
    # See mongodb uri documentation:
    # https://docs.mongodb.org/manual/reference/connection-string/
    client = self.connection.client
    hostname = client.hostname

    if hostname.startswith("srv://"):
        scheme = "mongodb+srv://"
        hostname = "mongodb+" + hostname
        client.hostname = hostname

    if not hostname.startswith(scheme):
        hostname = scheme + hostname

    if not hostname[len(scheme) :]:
        hostname += self.default_hostname

    if client.userid and "@" not in hostname:
        head, tail = hostname.split("://")

        credentials = client.userid
        if client.password:
            credentials += ":" + client.password

        hostname = head + "://" + credentials + "@" + tail

    port = client.port if client.port else self.default_port

    parsed = uri_parser.parse_uri(hostname, port)

    dbname = parsed["database"] or client.virtual_host

    if dbname in ("/", None):
        dbname = self.default_database

    options = {
        "auto_start_request": True,
        "ssl": self.ssl,
        "connectTimeoutMS": (
            int(self.connect_timeout * 1000) if self.connect_timeout else None
        ),
    }
    options.update(parsed["options"])
    options = self._prepare_client_options(options)

    if "tls" in options:
        options.pop("ssl")

    return hostname, dbname, options


def apply_kombu_monkey_patch():
    Channel._parse_uri = monkey_patch_channel_parse_uri
```

2024-06-04 16:02 UTC, Nusnus commented
@H4ad Thank you! Much appreciated!

> I did a monkey-patch on my code to use this change, I've been using since I opened this PR, this is the logs from yesterday:
> 
> ![Screenshot from 2024-06-04 09-47-47](https://private-user-images.githubusercontent.com/12551007/336459836-0159e548-0466-45f4-a46a-37d39c2166af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTcwMTEsIm5iZiI6MTcxNzUxNjcxMSwicGF0aCI6Ii8xMjU1MTAwNy8zMzY0NTk4MzYtMDE1OWU1NDgtMDQ2Ni00NWY0LWE0NmEtMzdkMzljMjE2NmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE1NTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MDM2MjNiMmM2OWI4YjUxZDVmMGU2NWE5ZTUzNDdjNGE3NDE2ZWMzYzMyOThkYmFhNmU2ZTc3MmIyMDI3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Z1Uidv4IrDSMwWP4x10kAIyOxL1ov3Pv8uL05jSFM4)
> 
> My monkey patch code is basically this:
> 
> ```python
> from kombu.transport.mongodb import Channel
> from pymongo import uri_parser
> 
> 
> def monkey_patch_channel_parse_uri(self, scheme="mongodb://"):
>     # See mongodb uri documentation:
>     # https://docs.mongodb.org/manual/reference/connection-string/
>     client = self.connection.client
>     hostname = client.hostname
> 
>     if hostname.startswith("srv://"):
>         scheme = "mongodb+srv://"
>         hostname = "mongodb+" + hostname
>         client.hostname = hostname
> 
>     if not hostname.startswith(scheme):
>         hostname = scheme + hostname
> 
>     if not hostname[len(scheme) :]:
>         hostname += self.default_hostname
> 
>     if client.userid and "@" not in hostname:
>         head, tail = hostname.split("://")
> 
>         credentials = client.userid
>         if client.password:
>             credentials += ":" + client.password
> 
>         hostname = head + "://" + credentials + "@" + tail
> 
>     port = client.port if client.port else self.default_port
> 
>     parsed = uri_parser.parse_uri(hostname, port)
> 
>     dbname = parsed["database"] or client.virtual_host
> 
>     if dbname in ("/", None):
>         dbname = self.default_database
> 
>     options = {
>         "auto_start_request": True,
>         "ssl": self.ssl,
>         "connectTimeoutMS": (
>             int(self.connect_timeout * 1000) if self.connect_timeout else None
>         ),
>     }
>     options.update(parsed["options"])
>     options = self._prepare_client_options(options)
> 
>     if "tls" in options:
>         options.pop("ssl")
> 
>     return hostname, dbname, options
> 
> 
> def apply_kombu_monkey_patch():
>     Channel._parse_uri = monkey_patch_channel_parse_uri
> ```

@auvipy I know you asked for tests, but I think this proves that it at least does what it is supposed to, in addition to also reviewing the code itself (which makes sense to me as-is).

I think we can go through and come back if someone reports an issue - what do you say?

2024-06-17 17:53 UTC, Nusnus commented
> LGTM then. We’ll wait for @auvipy to review it as well.

@auvipy hey bro - just giving a ping.

LGTM, see also: https://github.com/celery/kombu/pull/1976#issuecomment-2147486711

2024-06-18 16:17 UTC, auvipy approved these changes

2024-06-18 16:17 UTC, merged

2024-06-18 16:18 UTC, auvipy commented
we are fine with small patches with manual verification as well in case adding a test is too hard