enhance: allow users to disable broker heartbeats
celery/kombu pull request #1998
Opened 2024-05-12 19:30 UTC by smart-programmer

broker heartbeats clutter the logs console which prevents users from seeing important logs. this allows users to disable broker heartbeats if timeout isn't provided.

[reference issue](https://github.com/celery/kombu/issues/1997)

2024-05-13 04:03 UTC, auvipy requested changes
the change seems feasible, however, is it possible for you to add some additional tests for the change?

2024-05-30 13:24 UTC, FrankK-1234 commented
Hello,

I took the liberty to add a test case for this change. However I'm failing to add to a pull request as I'm new to git and I get a permission denied pushing to smart-programmer branch. No clue how to do it. I however attached a patch file to add the change in t/unit/test_mixins.py. Would that test case be enough for the proposed change? (I somehow cannot upload .patch so used .txt instead)
[test_mixins.txt](https://github.com/celery/kombu/files/15500550/test_mixins.txt)

2024-05-30 13:57 UTC, auvipy commented
thanks for the test! you have to open a PR on smart-programmer:enhance/disable-heartbeat-no-timeout branch. if you can't do that we will add the test from your provided code!

2024-05-30 16:12 UTC, auvipy commented
> Hello,
> 
> I took the liberty to add a test case for this change. However I'm failing to add to a pull request as I'm new to git and I get a permission denied pushing to smart-programmer branch. No clue how to do it. I however attached a patch file to add the change in t/unit/test_mixins.py. Would that test case be enough for the proposed change? (I somehow cannot upload .patch so used .txt instead) [test_mixins.txt](https://github.com/celery/kombu/files/15500550/test_mixins.txt)

or you can open a full PR with your tests and this PR's changes as well! we wil make sure both will get contributors credit

2024-05-31 11:45 UTC, FrankK-1234 commented
I've create a new PR #2016 with both the change and the test case.

2024-06-01 04:20 UTC, auvipy approved these changes

2024-06-01 04:21 UTC, merged