Resolving TypeError, during version unpacking
celery/kombu pull request #2098
Opened 2024-08-14 12:15 UTC by couzhei

This will make sure that the version unpacking doesn't stop connection to some versions of message brokers. For message brokers with normal-style version, say 3.13.6, 
```Pyhon
def version_string_as_tuple(s: str) -> version_info_t:
    """Convert version string to version info tuple."""
    v = _unpack_version(*s.split('.'))
    ...
```
will result in `['3', '13', '6']` list. But for newer releases of rabbitmq, say when you pull docker image using a specified version, in my case `4.0-rc` as discussed in this  [issue](https://github.com/celery/celery/issues/9161#issuecomment-2288083848) related to #2088 it becomes this:
```Python
['4', '0', '0+beta', '2', '6', 'g65c3daf']
```
which causes that `TypeError`.

2024-08-14 14:58 UTC, Nusnus requested changes
Thank you for the PR.

Please add tests and fix the lint error.

2024-08-21 05:54 UTC, couzhei commented
I really don't get the CI error. I even created a virtual environment from a 3.9 version, but it was okay there. I also almost always have this test failed:
```bash
===================================================== short test summary info =====================================================
FAILED t/unit/transport/test_redis.py::test_Redis::test_publish__consume - OSError: [Errno 9] Bad file descriptor

Results (37.34s):
    1181 passed
       1 failed
         - t/unit/transport/test_redis.py:1373 test_Redis.test_publish__consume
     315 skipped
Restoring 2 unacknowledged message(s)
```
Which I'm not sure why it happens when I run tests locally.

2024-08-21 05:59 UTC, auvipy reviewed
re run the job to see

2024-08-21 06:23 UTC, auvipy commented
we just need to fix the lint error

2024-08-21 06:25 UTC, couzhei commented
Thank you, my bad. I have never used pydocstyle, but I have just learned it.

2024-08-21 06:27 UTC, couzhei commented
> re run the job to see

I think I don't have the right to re-run a job.

2024-08-25 07:12 UTC, thedrow approved these changes

2024-08-25 07:12 UTC, merged

2024-11-20 11:23 UTC, SandeepaDevin commented
/python3.9/site-packages/kombu/transport/redis.py


GlobalKeyPrefixMixin | <class 'kombu.transport.redis.GlobalKeyPrefixMixin'>
InconsistencyError | <class 'kombu.exceptions.InconsistencyError'>
Mutex | <function Mutex at 0x7f1e4ee5eb80>
MutexHeld | <class 'kombu.transport.redis.MutexHeld'>
PRIORITY_STEPS | [0, 3, 6, 9]
READ | 1
VersionMismatch | <class 'kombu.exceptions.VersionMismatch'>
poll | <function poll at 0x7f1e4eeae3a0>
promise | <class 'vine.promises.promise'>
redis | None
register_after_fork | <function register_after_fork at 0x7f1e51c95f70>


I tried from supervisor and it seems like it cannot pick the redis version.

2025-01-15 08:05 UTC, auvipy commented
should we revert this?