Add native delayed delivery API to kombu
celery/kombu pull request #2128
Opened 2024-09-30 06:30 UTC by thedrow

This PR adds the native delayed delivery API to kombu so that it can be used without Celery if required.
The PR includes an example on how to do so.

2024-09-30 12:56 UTC, Nusnus requested changes
1. Add official documentation.
2. Make sure the CI passes.
3. Make sure you're rebased on main.

Also, I'm not sure about `kombu.delayed...`. Shouldn't it be in the RabbitMQ transport layer?

This feature is relevant only for RabbitMQ so it should be in the matching place in the code IMHO.

2024-10-06 12:07 UTC, thedrow commented
I thought about it and I prefer to keep the API in a separate module.
I included the example in our list of examples and added a short description which is enough documentation for most users.

The pre-commit check is failing for unrelated reasons.

2024-10-06 15:09 UTC, Nusnus submitted a review, later dismissed
> I thought about it and I prefer to keep the API in a separate module.
> I included the example in our list of examples and added a short description which is enough documentation for most users.
> 
> The pre-commit check is failing for unrelated reasons.

There's no problem leaving it in a separate module, but correct me if I'm wrong, this is a transport layer feature, so it should be in the transport.

This is a cosmetic change.

Apart from that, please add the version string to the docs with v5.5 (Current 5.4.2).

We don't expect any patch release soon so the next minor release will include your new feature.

Besides LGTM, thank you!

2024-10-06 16:37 UTC, Nusnus commented on docs/reference/kombu.native_delayed_delivery.rst
Please add version string

2024-10-06 17:09 UTC, thedrow commented on docs/reference/index.rst
> +    kombu.native_delayed_delivery
But that's where the transports are. This module is not a transport.

2024-10-07 12:29 UTC, auvipy reviewed
yes, Native Delayed Delivery API is to Transport layer, so logically, this should be inside the transport

2024-10-12 18:17 UTC, merged

2024-10-12 19:23 UTC, Nusnus commented
![CleanShot 2024-10-12 at 22 15 57@2x](https://github.com/user-attachments/assets/dcbd6f40-5442-4003-a855-ff90f03bb918)

Thank you for explaining @thedrow , but next time please just ping me here so I’ll review the fixes and approve the PR instead.
I need to confirm my review comments are resolved, or it loses its entire point 🤷‍♂️

Please pay attention next time, thank you.