Haim/feature/gcp pubsub on master
celery/kombu pull request #2147
Opened 2024-10-12 12:12 UTC by haimjether

Add support for GCP Pub/Sub 

* Add tests
* Add docs

Fix: https://github.com/celery/kombu/issues/705
Fix: https://github.com/celery/celery/issues/3984

2024-10-12 15:55 UTC, Nusnus requested changes
Please fix CI failures 🙏

2024-10-12 15:56 UTC, Nusnus requested changes
Also please change back to draft until the CI fully passes.
Feel free to ping me when it's ready for review!

2024-10-12 16:43 UTC, haimjether commented
> Please fix CI failures 🙏

@Nusnus , I can't re-trigger those without maintainer approval :(

2024-10-13 07:51 UTC, haimjether commented
> Also please change back to draft until the CI fully passes. Feel free to ping me when it's ready for review!

ping :)

2024-10-13 11:33 UTC, haimjether commented
My bad - I have last tiny nit,
would you mind if I push it  ?

2024-10-13 12:01 UTC, Nusnus commented
> My bad - I have last tiny nit,
> would you mind if I push it  ? 

Go for it 💯

2024-10-13 13:48 UTC, Nusnus approved these changes
Thank you for the great contribution!
Amazing work, end to end.

Well done 💯👏

2024-10-13 13:48 UTC, Nusnus commented on tox.ini
> +setenv =
Cool!

2024-10-13 13:49 UTC, merged

2024-10-13 13:51 UTC, Nusnus commented
I'm going to release a new version soon.
Anything else required on the Kombu side? @haimjether

2024-10-13 14:22 UTC, haimjether commented
@Nusnus ,
kombu's off the hook (for now) :) 

However this one https://github.com/celery/celery/pull/9351 
pretty mandatory for Flower to work correctly and is at Celery playground.