don't brpop if closed
celery/kombu pull request #2154
Opened 2024-10-14 19:42 UTC by thuibr

2024-10-14 20:39 UTC, Nusnus requested changes
Hey, thank you for the fix.
Can you please explain what and why is the change please?
Also, please add unit tests.

Lastly, we can mark this as draft for now and ready again after the above is answered & the CI fully passes.

Thanks!

2024-10-15 11:35 UTC, thuibr commented
Hi @Nusnus I was trying to debug https://github.com/celery/kombu/issues/1785 but this doesn't do it. I will follow your guidance once I find a fix.

2024-11-10 22:29 UTC, thuibr commented
@Nusnus this now reverts #1733 because that causes bugs for #1785.

2024-11-10 22:30 UTC, thuibr commented
I also don't really understand the rationale in #1733. Why would completing a `BRPOP` re-enqueue a message in redis?

2024-11-10 22:42 UTC, thuibr commented
Alternatively, I could see setting `socket_timeout` to something by default instead of `None`, which also fixes the issue.

```python
app.conf.broker_transport_options = {'socket_timeout': 5}
```

2025-01-14 09:33 UTC, auvipy commented
> Alternatively, I could see setting `socket_timeout` to something by default instead of `None`, which also fixes the issue.
> 
> ```python
> app.conf.broker_transport_options = {'socket_timeout': 5}
> ```

can you please elaborate bit more on the conclusion you draw?

2025-01-15 12:05 UTC, thuibr commented
> > Alternatively, I could see setting `socket_timeout` to something by default instead of `None`, which also fixes the issue.
> > ```python
> > app.conf.broker_transport_options = {'socket_timeout': 5}
> > ```
> 
> can you please elaborate bit more on the conclusion you draw?

I came to that conclusion empirically, through trial and error. My guess is that the workers are getting stuck somehow and providing a timeout instead of no timeout at all unblocks them. Does that answer your question?

2025-01-18 16:09 UTC, closed without merging