Added confirm_timeout argument to publish()
celery/kombu pull request #2167
Opened 2024-10-20 10:26 UTC by thedrow

When publishing a message in confirm mode, there was no way to specify the confirmation timeout in `publish()`.
This PR adds a new `confirm_timeout` argument to address that.

2024-10-20 17:10 UTC, Nusnus requested changes
The actual change is never tested @thedrow.
The unit test only covers that the new argument is being passed correctly down the stack, which is excellent. But the functionality of the `confirm_timeout` hasn’t really been tested. It doesn’t, for example, test that when the timeout is over, there’s an error, which validates that the new argument actually changes anything.

Lastly, shouldn’t there be a matching change in Celery for using this new flag? Or is it already unpacked as part of an existing flow and depends on the user adding it?

2024-10-20 18:26 UTC, thedrow commented
What you are talking about is an integration test, correct?

2024-10-21 10:50 UTC, Nusnus commented
> What you are talking about is an integration test, correct? 

Yes, correct :)

2024-10-23 08:08 UTC, thedrow commented
I have written the following integration test but it fails since even the smallest timeout possible is not enough for it to timeout:
```python

@pytest.mark.env('py-amqp')
@pytest.mark.flaky(reruns=5, reruns_delay=2)
class test_PyAMQPBasicFunctionality(BasicFunctionality):
    def test_publish_confirm_timeout(self, request):
        connection = Connection(
            hostname=os.environ.get('RABBITMQ_HOST', 'localhost'),
            port=os.environ.get('RABBITMQ_5672_TCP', '5672'),
            vhost=getattr(
                request.config, "slaveinput", {}
            ).get("slaveid", None),
            transport_options={
                "confirm_publish": True
            }
        )

        with connection.Producer() as producer:
            with pytest.raises(MessageNacked):
                producer.publish(
                    'test',
                    confirm_timeout=sys.float_info.min
                )
```

2024-10-24 14:56 UTC, thedrow commented
@Nusnus All Celery tests are passing.

2024-10-24 17:45 UTC, Nusnus commented
> I have written the following integration test but it fails since even the smallest timeout possible is not enough for it to timeout:
> 
> ```python
> @pytest.mark.env('py-amqp')
> @pytest.mark.flaky(reruns=5, reruns_delay=2)
> class test_PyAMQPBasicFunctionality(BasicFunctionality):
>     def test_publish_confirm_timeout(self, request):
>         connection = Connection(
>             hostname=os.environ.get('RABBITMQ_HOST', 'localhost'),
>             port=os.environ.get('RABBITMQ_5672_TCP', '5672'),
>             vhost=getattr(
>                 request.config, "slaveinput", {}
>             ).get("slaveid", None),
>             transport_options={
>                 "confirm_publish": True
>             }
>         )
> 
>         with connection.Producer() as producer:
>             with pytest.raises(MessageNacked):
>                 producer.publish(
>                     'test',
>                     confirm_timeout=sys.float_info.min
>                 )
> ```

Is there a way to manually test it maybe?

2024-10-24 17:46 UTC, Nusnus requested changes
> I have written the following integration test but it fails since even the smallest timeout possible is not enough for it to timeout:
> 
> ```python
> @pytest.mark.env('py-amqp')
> @pytest.mark.flaky(reruns=5, reruns_delay=2)
> class test_PyAMQPBasicFunctionality(BasicFunctionality):
>     def test_publish_confirm_timeout(self, request):
>         connection = Connection(
>             hostname=os.environ.get('RABBITMQ_HOST', 'localhost'),
>             port=os.environ.get('RABBITMQ_5672_TCP', '5672'),
>             vhost=getattr(
>                 request.config, "slaveinput", {}
>             ).get("slaveid", None),
>             transport_options={
>                 "confirm_publish": True
>             }
>         )
> 
>         with connection.Producer() as producer:
>             with pytest.raises(MessageNacked):
>                 producer.publish(
>                     'test',
>                     confirm_timeout=sys.float_info.min
>                 )
> ```

Is there a way to manually test it maybe?
Also, please fix conflicts and rebase on `main`

2024-10-25 17:20 UTC, thedrow commented
If the integration test doesn't work then it will be hard to reproduce this without an extremely busy production environment.
I'll rebase.

2024-10-26 10:15 UTC, thedrow commented
@Nusnus Rebased. Please merge once CI is green.

2024-10-26 16:25 UTC, Nusnus approved these changes
> If the integration test doesn't work then it will be hard to reproduce this without an extremely busy production environment. I'll rebase.

This means we can’t confirm that this fix actually works, but I also understand the difficulty of testing that.
I’ll take your word on it @thedrow then to allow us to move forward.

Approved.

2024-10-26 16:25 UTC, merged